### PR TITLE
Chromicle-21 Add the filter option.

### PR DESCRIPTION
**Pull request by jaindiv26**
**Description** Added the filter button in the menu toolbar and clicking upon the button opens a bottom sheet.

**Issue no** #25 

**Screenshot**

Screenshot_2019-10-22-15-27-03-188_com example android codeforces

Screenshot_2019-10-22-15-27-06-603_com example android codeforces

### CODE REVIEW

**Comment by jaindiv26** [comment]
It's a WIP, will submit the rest tomorrow.

**Comment by jaindiv26** [comment]
@Chromicle Please review this PR, the filter option is added.

**Comment by Chromicle** [comment]
> @Chromicle Please review this PR, the filter option is added.

Can you please solve the travis issue for spotless you can run `./gradlew spotlessApply`

**Comment by jaindiv26** [comment]
@Chromicle I'll fix the travis issue and push my changes in an hour.

**Comment by jaindiv26** [comment]
@Chromicle Travis issue is fixed.

**Pull request merged**
