### PR TITLE
Added Readme.md file

### PR DESCRIPTION
**Pull request by jaindiv26**
Added Readme.md file

Issues:
#21

### CODE REVIEW

**Comment by jaindiv26** [comment]
Okay

**Comment by Chromicle** [comment]
Are you doing this @jaindiv26

**Comment by jaindiv26** [comment]
@Chromicle I'll add those couple of screenshots and submit the PR in 30 minutes.

**Comment by jaindiv26** [comment]
@Chromicle I've added the screenshots, please merge this PR and after I'll edit the README.md file directly from the GitHub console

**Comment by Chromicle** [comment]
You can directly do that in your fork I will merge directly then 
And the way you going will increase the repo size the way I will prefer is upload it somewhere and get the links and use them here

**Comment by jaindiv26** [comment]
@Chromicle Okay, I'll directly merge into my fork. And uploading the images somewhere has the problem that the image URL can get invalid, that's why I've added a screenshot folder.

**Comment by jaindiv26** [comment]
@Chromicle How does it look now? 
https://github.com/jaindiv26/Codeforces/blob/master/README.md

**Pull request merged**
