### PR TITLE
fix: Version bump

### LINKED ISSUE #31: Bump the gradlew versions
**Describe the bug**
Current versions of the gradlew and some dependencies are outdated, Update the versions

**Would you like to work on the issue?** (Yes/No)
No

### PR DESCRIPTION
**Pull request by krharsh17**
Fixed #31 

Changes: Updated the build.gradle files to set the versions of all dependencies and gradle to the latest available.

### CODE REVIEW

**Comment by krharsh17** [comment]
> You pushed the other PR commits also please make sure that not happens but great work: tada

Sure thing.

**Comment by Chromicle** [comment]
@krharsh17 if you need any help please let me know

**Comment by krharsh17** [comment]
I reverted the androidx commit, and rebased the forked branch, but since the androidx PR got merged, so I had to merge those changes in this PR to avoid a merge conflict due to this PR on upstream. So now this PR is back in level with the upstream. I'll commit the version update changes now.

**Comment by krharsh17** [comment]
The rebase wasn't successful I think, and now there's a lot of errors in the CI. Any chance it can be solved from here? Or shall I create a fresh PR for this task?

**Comment by Chromicle** [comment]
> The rebase wasn't successful I think, and now there's a lot of errors in the CI. Any chance it can be solved from here? Or shall I create a fresh PR for this task?

Ok, if want to create new PR then go on but do not repeat this evry time

**Pull request closed without merging**
