### PR TITLE
Add navigation drawer

### LINKED ISSUE #35: Add Navigation drawer
**Describe the feature you'd like**
Add the Navigation drawer for
1. Blog entities
2. Recent submissions 
3. sign in with other user

Note: No need to implement the features just make navigation drawer

**Would you like to work on the issue?** (Yes/No)
No

### PR DESCRIPTION
**Pull request by krharsh17**
Fixed #35 

Changes: 
Added navigation drawer as specified

Screenshots of the change: 
Closed
Open

### CODE REVIEW

**Comment by krharsh17** [comment]
Okay, I'll make the change

**Comment by krharsh17** [comment]
@Chromicle How do I run spotlessApply on windows?

**Comment by Chromicle** [comment]
You can run by `gradlew spotlessApply`

**Comment by krharsh17** [comment]
Screen1
Screen2

**Pull request merged**
